name: Reusable Trivy Security Scan

on:
  workflow_call:
    inputs:
      docker-image-name:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.docker-image-name }}:latest'
          format: 'table'
          exit-code: '1' # Crashes pipeline if CRITICAL vulnerabilities are found
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'